version: '3.1'

services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres:alpine
    container_name: postgres-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  app:
    build: ./
    depends_on:
      - redis
      - postgres
    image: backend:latest
    container_name: backend
    volumes:
      - ./:/backend
    ports:
      - "8080:8080"
    expose:
      - 8080
